- hosts: docker
  tasks:
  - name: "configuring docker"
    block:
    - name: "installing apache httpd"
      package:
        name: httpd
        state: present
    - name: "creating webpage"
      template:
       dest: /var/www/html/
       src: ./docker.html
    - name: "starting the httpd service"
      command: /usr/sbin/httpd
    rescue:
    - debug:
        msg: "something miss contact to developer"

    always:
    - debug:
        msg: "THANK YOU"

